### ISSUE TITLE
Handling endianness of individual values when unpacking

### ISSUE THREAD

**Issue by altendky** [eerimoq/bitstruct#1]
As every open source query should start...  thank you!  Bit (un)packing has always been something that annoyed me to have to recode each time I needed it and this helps alleviate that.

One piece that seems like it may be missing (unless I haven't through through `byteswap()` well enough) is endianness awareness when unpacking the data.  `struct` allows for endianness control via `<` and `>` in the format string but it appears that is not present in `bitstruct`.  Am I missing it?  If not, would you be interested in this feature if I developed it?

It seems to me that, for signed integers, the sign extension and byte-order correction would need to occur prior to the `int()` conversion.

Thanks for any thoughts you have on this.

**Comment by eerimoq** [comment]
I like the idea to have < and > in the format string to mimic the struct module.

The byteswap-function was written to handle endianess, but it's a silly user interface. Most users wants the interface requested by you.

Feel free to implement it and add a pull request and I'll most likely accept it :)

**Comment by altendky** [comment]
First run at this implemented in a1dff1f96e8b113fefb7296e637c010654e1a6a6.  Passes old and new tests with Python2 and Python3.  I have not really applied this yet so I will do so and then put in a pull request if it seems to be working well.  Just wanted to give you a chance to review it sooner that later to make sure it's heading the right direction for acceptance.

**Comment by eerimoq** [comment]
One question:

What's the reason for adding < or > before every value (s/u/f/b <width>) in the format string, and not just at the beginning of the format string? It would be great if you can give an example of when this functionality is required. A machine is little or big endian, it does not change endianness for every value in a bit field. =)

Some background information about the byteswap() function:

I often use bit flelds in c data structures. Although the c standard of bit fields is not well defined, and compilers may implement in different ways, I would like to be able to decode them with this module. In the example below the value of 'b' is stored in memory as bit 0 in buf[1] and bits 3-7 in buf[0]. To decode this with this module I have to use the byteswap-function to buf before trying to decode it with the format string "u3u6u7". Of course, it's impossible to handle this case with < and >, since you don't know that it is a 16 bits container. It should as well be a 32 bits container. The format string does not contain this information.

    #include <stdio.h>
    #include <stdint.h>
    
    struct foo_t {
        uint16_t a : 3;
        uint16_t b : 6;
        uint16_t c : 7;
    };
    
    int main()
    {
        uint8_t buf[2];
        struct foo_t *foo_p = (struct foo_t *)buf;
    
        foo_p->a = 2;
        foo_p->b = 0x3f;
        foo_p->c = 0;
    
        printf("0x%02x 0x%02x\n", buf[0], buf[1]);
    
        return (0);
    }
    
    Compilation and execution on a little-endian machine.

    $ gcc main.c && ./a.out
    0xfa 0x01

**Comment by altendky** [comment]
My use case is CAN bus messages.  They are considered an 8-byte array of data with values packed inside.  The two main higher-level protocols on CAN (CANopen and J1939) both use little endian for each packed value regardless of what processor they are run on.  There's no particular reason each signal can't individually be different endianness.

Was bitstruct able to unpack your fields before my change?  It shouldn't have had any effect on this example since each value was individually less than 8-bits long so there is no endianness relevance within a single value.

I plan to provided a more complete response later.

```
altendky@tp:~$ python3
Python 3.4.3+ (default, Oct 14 2015, 16:03:50) 
[GCC 5.2.1 20151010] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bitstruct
>>> bitstruct.unpack('<u3<u6<u7', bytearray([0xfa, 0x01]))
(7, 52, 1)
>>> bitstruct.unpack('<u3<u6<u7', bytearray([0x01, 0xfa]))
(0, 3, 122)
>>> bitstruct.unpack('>u3>u6>u7', bytearray([0x01, 0xfa]))
(0, 3, 122)
>>> bitstruct.unpack('>u3>u6>u7', bytearray([0xfa, 0x01]))
(7, 52, 1)
>>>
```

**Comment by altendky** [comment]
Here we go.

```
>>> import bitstruct
>>> bitstruct.unpack('u7u6u3', bytearray([0xfa, 0x01]))
(125, 0, 1)
>>> bitstruct.unpack('u7u6u3', bytearray([0x01, 0xfa]))
(0, 63, 2)
>>> 0x3f
63
```

So the endianness that you are concerned with relates seemingly to the grouping of the 'words' (not necessarily the system word size, 16-bits in this case) in which the bit strings are packed.  I'm not worried about that and instead need to control the endianness with which the bits are interpreted once extracted from the 'stream'.

I believe that both features are relevant but unique.  For your use case I see little need to provide the functionality as part of the format string and can exist as a separate function (as you have).

```
>>> bitstruct.unpack('u7u6u3', bytearray(bitstruct.byteswap('8', [0xfa, 0x01])))
(0, 63, 2)
```

 This could certainly be adjusted to something like the following for more 'integration' but I'm not sure it adds a lot.  It would be easy though.

```
>>> bitstruct.unpack('u7u6u3', bytearray([0xfa, 0x01]), swap_fmt='8'))
(0, 63, 2)
```

I just looked back at `struct` and had thought they had done endianness the way I did, a modifier allowed for each element, but this does not appear to be the case.  They do a single modifier for the entire set of elements.  I can see the argument for consistency though I would rather not remove the flexibility.  Perhaps a format like `<<u7u6u3` could be used to force the default for interpretation to be `<` for the rest of the format elements?

As a side note on the C code, I am of the opinion that bit-packed structures are an internal memory optimization technique not a portable packing and unpacking tool (consider SO question [Bit fields portability](http://stackoverflow.com/q/25345691)).  But, I don't think that opinion is terribly relevant to this conversation.  Regardless, control of both the endianness of the words in the stream (your need) and the endianness of the data fields once extracted from the stream (my use case) are valid.

**Comment by eerimoq** [comment]
First of all, this is how to use byteswap():

    >>> import bitstruct
    >>> bitstruct.unpack('u7u6u3', bitstruct.byteswap("2", bytearray([0xfa, 0x01])))
    (0, 63, 2)

The format "2" means that the next two bytes should be swapped, in this case byte 0 and byte 1.

We don't have to discuss bit fields. It was just an example usage. It's important that the bitstruct module can be used on "any" stream of bits. So, if it is important to allow endianness selection per field in the stream, I guess I have to accept it. The only drawback is worse pack/unpack-performance, but it's pretty terrible already. I only focused on making the user interface as clean as possible.

What about inheriting the endianness modifier from the previous value? That simplifies the format string if all values have a common endianness. I.e. only a endianness modifier at the beginning of the string, just like the struct module.

**Comment by altendky** [comment]
I did a super basic profile as below and found that with that format string (no specification of endianness) they are basically the same within the consistency of runtimes I measured (roughly 3.7 seconds for the 100,000 cycles or 37us per).  I guess all I derive from that is that it doesn't slow down the previous usage.  Upon further inspection it might be 3.7 vs. 3.5, but still pretty close.  Actually exercising my addition via the format string `u1u1<s14<u17<u9<f32` runs 6s+.  All big-endian (so format string effect but no actual translation) is around 3.9s.

Note that this is the very first Python profiling I've ever done, so...  I wouldn't be surprised if the results are erroneous.  But for the moment it makes me a little less concerned about the performance effect of this change for people not using it's features.  Also, it seems to point out that the performance hit for parsing (all `>` formats) is fairly low.  But, I suspect there is opportunity for improvement of the actual translation.

Still, I do see some benefit to the consistency with `struct` and the somewhat simpler format string.  I'll see if I can come up with a good combination to propose.

```
    def test_profile(self):
        import math
        import cProfile
        data = (0, 0, -2, 65, 22, math.pi)
        format = 'u1u1s14u17u9f32'
        # packed_a = pack(format, *data)
        repeat = lambda x: [pack(format, *data) for i in range(x)]
        cProfile.runctx('repeat(100000)', locals(), globals())
```

**Comment by eerimoq** [comment]
Does the implementation in commit https://github.com/eerimoq/bitstruct/commit/ba7f2db61eb2a84f9144345a5b5786133c33585e meet your requirements? The part of your testcase that used pack() and unpack() passed and I take that as a good indication that it works as you want.

**Comment by altendky** [comment]
I had been off on other parts of my application and had been planning on circling back around to this soon.  I'm going to go ahead and test and compare them but it appears that you have implemented something that may be closer to bit-endianness than byte-endianness based on the simple reversal of all the bits.  I may well have written a poor 'test suite' that didn't sufficiently describe or check this feature.  Off to actually test now.

**Comment by eerimoq** [comment]
Ahh okay yes, i implemented bit reversal of the whole value indeed.
Although, in many cases it's possible to combine the usage of byteswap()
and bit reversal to get the suitable effect.

Let me know if the implementation has to be changed.

Have a nice weekend. :)

**Comment by altendky** [comment]
in `insert hash here` I went ahead and reapplied my tests and endianness conversion on top of your format parsing code.  I did push the translation call back down into the `_[un]pack...` functions, but if you prefer I think I could pull it back out pretty quick.  I also changed the comments to refer to byte order rather than bit order.

**Comment by eerimoq** [comment]
Earilier you mentioned CANOpen and J1939. Can you post a url to example messages and specifications of those protocols? I'm reluctant to accept byte endianness for values. I havn't seen a good use case and need facts to accept the fact that a byte swap identifier per value is needed.

**Comment by altendky** [comment]
Fair enough.  :]

I don't directly need per-value specification of big or little endian right now, and hopefully never will.  That'd be one messy message format.  So, you don't have to push too hard to make it a single overall format setting.  Actually, if I had looked back at `struct` more carefully and noticed that it only had a single specifier at the beginning of the format I may not have added multiple here.  I just usually try to solve a problem more generally than my particular need at the moment.  Also, I think your concept/application of endianness might be more inline with the `struct` usage than mine is.  This leads me to wonder if a different option than `<` and `>` may be more appropriate to avoid confusion.  Even a separate parameter outside the format string.  *shrug*

But, I do need to be able to interpret bit streams with little endian values where not all values are the same length.  The last paragraph and last table on the [Kvaser J1939 introduction page](https://www.kvaser.com/about-can/higher-layer-protocols/j1939-introduction/) shows `0x1ADF` packed as `DF 1A`.  For CANopen, about halfway down this [CANopen basics page](http://www.canopensolutions.com/english/about_canopen/device_configuration_canopen.shtml) is a reference to little endian and an example showing OD entry `0x1017` coded as `17 10`.  At least for CANopen, elements can be any length including not being multiples of eight.  I have less experience with J1939 so I may yet find that it bans that but the particular device I'm working with does at least have values which are less than 8 bits.

Is there a particular concern you have?  Hassle of maintenance?  Performance?  Aside from the fact that it's your repo :] I do appreciate your concern for keeping it clean.

**Comment by eerimoq** [comment]
My concern is that I don't want to add code for a use case that is rarely used. I prefer to keep the API and source code as clean as possible. I'm sure there are more use cases, that we don't think about now, that requires more code and confuses the user for than it helps. Sometimes it's better to handle the special cases in a separate module, that in turn can use this module. Then, in the furute, it might turn out that the two modules should be merged. Who knows =)

The CAN examples can all use the current module to pack/unpack the values. The first two by using the byteswap() function before calling unpack. For the third, well, if the <8 bits are crossing a byte boundary there might be problems to unpack, but most of the time it should work.

**Comment by altendky** [comment]
Alrighty, thanks for your time and consideration.  I'll just keep using my branch for now.  Maybe in time I'll find that I really am creating a problem that doesn't actually exist.

**Comment by eerimoq** [comment]
Thanks for your time too. Let's see what the future brings :)

**Comment by Electrolytebackbone-even** [comment]
@altendky https://stackdev.space/questions/problem-with-a-byte-order-reversal-function
