### ISSUE TITLE
Emulating C bitfield structures using bitstruct

### ISSUE THREAD

**Issue by mleroy003** [eerimoq/bitstruct#13]
Hello, I am trying to generate memory layout of big-endian and little-endian C structures using bitstruct.

For example, to emulate this structure : 
typedef struct {
	uint32_t	a:28;
	uint32_t	b:4;
} MyStruct;

It is ok for big-endian structures, it is consistent with the byte stream consistent with the ABI of big endian processors (SPARC, PowerPC, ...) : 

import bitstruct
MyStructFmt = '>u28u4>'
s1_packed = bitstruct.pack(MyStructFmt, 0x1234567, 0x8 )
print('b\'',''.join('{:02x}'.format(letter) for letter in s1_packed), sep='', end='\'\n')
b'12345678'

But trying to emulate a little endian processor like AMD64 fails : 

MyStructFmt = '>u28u4<'
s1_packed = bitstruct.pack(MyStructFmt, 0x1234567, 0x8 )
print('b\'',''.join('{:02x}'.format(letter) for letter in s1_packed), sep='', end='\'\n')
b'674523**18**'

because b'674523**81**' is expected instead ...

Any idea ?

**Comment by eerimoq** [comment]
I don't know the C standard very well, but I'm sure bit fields have lots of undefined behavior. Bit field memory layout probably depends on which compiler you use, and I'm not sure bitstruct can be used to pack/unpack all variants.

https://en.cppreference.com/w/c/language/bit_field

**Comment by mleroy003** [comment]
As far I know, the compiler behaviour is constrained by the processor + OS couple application binary interface.
I used many C compilers/cross-compilers under many flavours of Unix, Linux, Cygwin under Win32 and Win64 but also real-time OS like VxWorks and RTEMS and on 68k, PowerPC in big endian mode, x86 and AMD64 processors. The way the bitfields are stored in memory was always consistent when using the "packed" option or pragma, and without using it in the cases there is no alignment problems:
the bit order is never reversed in the bytes w.r.t. the fields, but the way the bitstream of the structure fields are stored in a byte stream only depends on the "endianness" of the processor:
- on the big endian processors I used, the fields are serialized in the order of their declaration, starting with the most significant bits of the field and the most significant bits of the bytes;
- on the little endian processors, the fields are serialized in the order of their declaration, but starting with the least significant bits of the fields and also the least significant bits of the bytes.

It seems that in little endian mode, bitstruct serializes the fields starting with their least significant bit, but the bytes are filled starting with their most significant bits.

**Comment by eerimoq** [comment]
This is the best I can come up with: ``binascii.hexlify(bitstruct.byteswap('4', bitstruct.pack('u4u28', 8, 0x1234567)))``

Any improvement to bitstruct making this cleaner is welcome. I'll not redesign this myself as I have no need for it atm.
