### ISSUE TITLE
raw format on incomplete bytes

### ISSUE THREAD

**Issue by qchateau** [eerimoq/bitstruct#14]
```py
import bitstruct
print(bitstruct.unpack(">r4>", b"\xff")[0].hex())
print(bitstruct.unpack("<r4<", b"\xff")[0].hex())
print(bitstruct.unpack(">r4<", b"\xff")[0].hex())
print(bitstruct.unpack("<r4>", b"\xff")[0].hex())
```
outputs
```
f0
f0
f0
f0
```

I would expect
```
0f
0f
0f
0f
```

Is it a corner case or is there a rationale for this behavior ?
In any case, I don't think this is documented, or did I miss something ?

**Comment by eerimoq** [comment]
It's a corner case, and I agree, I would expect `b'\x0f'` as well. So far I've only used the raw format specifier for multiple of 8 bits, which works as expected. Feel free to submit a PR with a fix.

**Comment by qchateau** [comment]
Though as I dug further, I noticed your latest release changes this behaviors explicitly right ?

Looking at this specific case seems weird but as I found out since I opened this issue, it is also necessary to make pack/unpack symmetrical.

After all I think it's the "right" behavior

**Comment by eerimoq** [comment]
I don't really remember, but it looks like all raw tests are with a multiple of 8 bits, so I doubt I had this exact case in mind.

Good point, symmetry is important and required.
