### ISSUE TITLE
Pypy - Bitstruct C Extension compile error

### ISSUE THREAD

**Issue by maxchill** [eerimoq/bitstruct#18]
I was looking to use Pypy to test performance / compatibility.  Validate claims of 4x average performance improvement over CPython.  Howevev, I got a bitstruct c extension compile error.  It doesn't look too complicated, so wanted to document so myself, or yourself could see if fixable.

The version I used is below
- https://bitbucket.org/pypy/pypy/downloads/pypy3.6-v7.3.0-linux64.tar.bz2
- https://www.pypy.org/download.html#id33

To reproduce i did the following
```
pypy -m ensurepip
pypy -m pip install bitstruct
```

The following is the C extension error I got.
```
Running bitstruct-8.9.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-obznzsas/bitstruct-8.9.0/egg-dist-tmp-wvv9y33r

bitstruct/c.c: In function ‘pack_float_16’:

bitstruct/c.c:155:5: warning: implicit declaration of function ‘_PyFloat_Pack2’; did you mean ‘PyFloat_Check’? [-Wimplicit-function-declaration]

     _PyFloat_Pack2(PyFloat_AsDouble(value_p),

     ^~~~~~~~~~~~~~

     PyFloat_Check

bitstruct/c.c:157:20: error: ‘PY_BIG_ENDIAN’ undeclared (first use in this function); did you mean ‘BIG_ENDIAN’?

                    PY_BIG_ENDIAN);

                    ^~~~~~~~~~~~~

                    BIG_ENDIAN

bitstruct/c.c:157:20: note: each undeclared identifier is reported only once for each function it appears in

bitstruct/c.c: In function ‘unpack_float_16’:

bitstruct/c.c:168:13: warning: implicit declaration of function ‘_PyFloat_Unpack2’; did you mean ‘_PyPyFloat_Unpack8’? [-Wimplicit-function-declaration]

     value = _PyFloat_Unpack2(&buf[0], PY_BIG_ENDIAN);

             ^~~~~~~~~~~~~~~~

             _PyPyFloat_Unpack8

bitstruct/c.c:168:39: error: ‘PY_BIG_ENDIAN’ undeclared (first use in this function); did you mean ‘BIG_ENDIAN’?

     value = _PyFloat_Unpack2(&buf[0], PY_BIG_ENDIAN);

                                       ^~~~~~~~~~~~~

                                       BIG_ENDIAN

WARNING: Failed to build the C extension.

zip_safe flag not set; analyzing archive contents...

Moving bitstruct-8.9.0-py3.6.egg to /opt/pypy3.6-v7.3.0-linux64/site-packages

Adding bitstruct 8.9.0 to easy-install.pth file
```

**Comment by eerimoq** [comment]
If there is an easy solution, please implement it. It there isn't, I suggest updating `setup.py` not to build the C-extension when `pypy` is used.

**Comment by eerimoq** [comment]
Any progress?

**Comment by maxchill** [comment]
Some further investigation shows PyPy only implements a subset of the Python CAPI, so not a quick fix.  I now understand that despire the error, the code falls back to pure python, and I confirm that works with PyPy with large performance boost.  So I'm currently testing python variant detection, so it skips C Extension compile for pypy and possibly jython.  I'll submit a patch sometime this week.

**Comment by eerimoq** [comment]
I modified setup.py to only build the C extension on CPython 3. That should fix the PyPy compile error output.

Part of release 8.10.0.
