### ISSUE TITLE
Packing of booleans does not respect bit order

### ISSUE THREAD

**Issue by baileyji** [eerimoq/bitstruct#19]
Documentation provides the following example:

`bitstruct.pack('u5s5f32b1r13t40', 1, -1, 3.75, True, b'\xff\xff', 'hello')`
Out[68]: b'\x0f\xd0\x1c\x00\x00?\xffhello'

`bitstruct.pack('<u5s5f32b1r13t40', 1, -1, 3.75, True, b'\xff\xff', 'hello')`
Out[69]: b'\x87\xc0\x00\x03\x80\xbf\xff\xf666\xa6\x16'

Booleans and u1 do not perform as expected, maintaining MSB ordering.
`bitstruct.pack('>b1b1p6',True,True)`
Out[73]: b'\xc0'
`bitstruct.pack('<b1b1p6',True,True)`
Out[74]: b'\xc0'

Further investigation seems to suggest that padding is being added at the LSB end of things when fields are less than a byte:
bin(int(bitstruct.pack('>u7',0b11).hex(),16))
Out[119]: '0b110'  #I would expect 0b11
bin(int(bitstruct.pack('<u7',0b11).hex(),16))
Out[120]: '0b11000000'

**Comment by eerimoq** [comment]
There is nothing wrong, bitstruct preforms as expected. ``>`` and ``<`` means nothing for fields of one bit, as one bit is the same reversed. Note how ``>`` and ``<`` does not change the bit order within bytes, but within the bit fields themselves.

You have to do ``bin(int(bitstruct.pack('p1u7',0b11).hex(),16))`` to get ``0b11`` in your later example.

**Comment by baileyji** [comment]
I'll go look at some more test cases. I'm trying to use the library for prepping data for some FPGA registers and I'm a bit unclear from the cod how things will work with ordering of odd bit lengths fields.

For instance if I have a 32 bit register (0:31) and I have booleans at bits 1-6, reserved space at 0 and 7-11, and a 19 bit uint from 12:31 I was thinking the string should be '<p1 b1b1 b1b1 b1b1 p6 u19', but that does not work for packing and unpacking as I'd expect pack( '<p1 b1b1 b1b1 b1b1 p5 u19', True, True, False, False, True, False, 0x7ffff).hex() to result in 0xFFFFE026 but it results in 0x640ffffe.

**Comment by eerimoq** [comment]
What about ``pack('u19p6b1b1b1b1b1b1p1', 0x7ffff, False, True, False, False, True, True).hex() = 0xffffe026`` ? 6 padding bits are required to get the output you want.

**Comment by baileyji** [comment]
Thanks for the tip, that did it. I would have found it helpful if the docs could be a bit clearer on the bit ordering implications of the format string.
