### ISSUE TITLE
bitstruct.c is not pickleable

### ISSUE THREAD

**Issue by andlaus** [eerimoq/bitstruct#24]
The C implementation of `bitstruct`, `bitstruct.c` is currently not [pickleable](https://docs.python.org/3/library/pickle.html). This leads to issues for multiple users of `cantools` [[1]](https://github.com/cantools/cantools/issues/271), [[2]](https://github.com/cantools/cantools/issues/312), [[3]](https://github.com/cantools/cantools/issues/271).

**Comment by eerimoq** [comment]
Fixed in version 8.12.0.

**Comment by andlaus** [comment]
wow, that was quick. Thanks a lot!
