### ISSUE TITLE
Allow 'compiled' formats for unpack()

### ISSUE THREAD

**Issue by altendky** [eerimoq/bitstruct#3]
I am going through and improving the performance of my applicaiton including a little bit of looking around at the libraries I'm using.  Since you expressed interest in better performance I thought I'd share this minor tweak I made to allow 'compiled' formats like the `re` module.  https://github.com/altendky/bitstruct/commit/53fd50cf42473bacc49be308eae16536a93d1a1a  It's probably not the cleanest just using the `list` check like that but a little extra work for a `CompiledFormat` class would tidy that up.

Anyways, thanks again.

**Comment by eerimoq** [comment]
Thanks for the suggestion. I often use the ``re`` module and compiled patterns and I've had similar ideas as you are describing. I'll keep it in mind!

**Comment by eerimoq** [comment]
Implemented but didn't give enough time save to be useful. Closing issue.
