### ISSUE TITLE
Question: How to reproduce binary with a specific structure that is not multiples of 8? 

### ISSUE THREAD

**Issue by CiaranWelsh** [eerimoq/bitstruct#32]
Hello, I was wondering if you could help me. I have a 64-bit int which encodes some data in binary. I'm trying to use bitstruct to pack/unpack the data. Bitstruct seems to work well when the parts of the 64 bit int are multiples of 8, but less so when they are not. For example, 

```
expected = 12987458926396440779
```
Within this data set are the following: 
```
f = a constant. Its always 11.  bits 63, 60
e = 17355                               bits 59, 44
d = 9301                                 bits 43, 30
c = 45                                     bits 29, 20
b = 6                                      bits 19, 16
a = 203                                   bits 15, 0
```
In binary, this 64-bit int looks like this: 

```
f        e                               d                         c                     b      a    
1011 0100001111001011 10010001010101 0000101101 0110 0000000011001011
```

which you can get with :

    >>> bin(expected)

What I'm trying to do is create a format string that reproduces this format so that I can both read and write binary using your tool. So far, the best I've been able to come up with is: 

```
import bitstruct
rep = bitstruct.pack(
    "u16 u4 u10 u14 u16 u4",
    203,
    6,
    45,
    9301,
    17355,
    11,
)

x = int.from_bytes(rep, byteorder="little")

print("pxl ", rep, x, hexlify(rep), bin(x))
```

which outputs:
```
reproduced  b'\x00\xcb`\xb6ET<\xbb' 13491751242084436736 b'00cb60b645543cbb' 0b1011101100111100010101000100010110110110011000001100101100000000
```
Clearly `13491751242084436736 != 12987458926396440779` so I'm either doing something wrong or your tool doesn't support such a case. Since I'm guessing the former, would you be kind enough to help me out? 

Thanks, 
Ciaran

**Comment by eerimoq** [comment]
```python
