### ISSUE TITLE
Feature Request: decoding error handler.

### ISSUE THREAD

**Issue by mrbell321** [eerimoq/bitstruct#33]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff
Not a bug as much as a feature request. 0xff is obviously not valid utf-8, but it would be great if we could specify how to handle decoding errors. Kind of like how bytes has `decode("utf-8", errors="backslashreplace")`

**Comment by mrbell321** [comment]
Any thoughts on how to implement it?
My first idea was to have a new format 'T'(as opposed to 't'), but that pattern really only allows for one error handling method. So if someone, instead, wanted 'ignore' or one of the other options, they'll have to come up w/ a different letter and update the library.

If we can solve it nicely, it could also be nice to allow other codecs besides UTF-8

**Comment by eerimoq** [comment]
Implemented it in Python here: https://github.com/eerimoq/bitstruct/commit/35c7c28af3908ceffb2e90cb684da1e566d2e0d1

C implementation is not started and might take a while to complete.

**Comment by eerimoq** [comment]
Please test it and then I'll publish it to PyPI.

**Comment by eerimoq** [comment]
@mrbell321  Any feedback?

**Comment by mrbell321** [comment]
Sorry, I've been sidetracked on other things.
Looks reasonable to me, but can we update:
```python
def compile(fmt, 
                 names=None, 
                 text_encoding='utf-8',
                 text_errors='strict'):
    """Compile given format string `fmt` and return a compiled format
    object that can be used to pack and/or unpack data multiple times.
    Returns a :class:`~bitstruct.CompiledFormat` object if `names` is
    ``None``, and otherwise a :class:`~bitstruct.CompiledFormatDict`
    object.
    See :func:`~bitstruct.pack_dict()` for details on `names`.
    """

    if names is None:
        return CompiledFormat(fmt, text_encoding=text_encoding, test_errors=test_errors)
    else:
        return CompiledFormatDict(fmt, names, text_encoding=text_encoding, test_errors=test_errors)
```

**Comment by eerimoq** [comment]
Makes sense. Added. Part of 8.17.0.
