### ISSUE TITLE
Memory leak in c.compile

### ISSUE THREAD

**Issue by jmdelaney8** [eerimoq/bitstruct#34]
I've been using `cantools==37.1.2` which uses `bitstruct >= 8.14.1` and noticed that the memory usage of `cantools.database.can.Message` grows unbounded. I think I've traced it down to the usage of `bistruct.c.compile`

Here's example code that shows the memory growth of `c.compile`. I've replicated the functions usage from `cantools`: https://gist.github.com/jmdelaney8/1d7cca8dc6ccc7bba0894eb358729591

Running this script, `tracemalloc` reports that `bistruct.c.compile` uses ~300MB of memory every 10 seconds. After 8 minutes it has used nearly 2.5GB of memory.

Here's where `c.compile` is used in `cantools` https://github.com/cantools/cantools/blob/92f4c020df296402040eb84139bf7678a2d36f7b/cantools/database/utils.py#L253

**Comment by eerimoq** [comment]
Should be fixed in 8.16.1. Thanks for reporting.

**Comment by jmdelaney8** [comment]
Looks fixed on my end too. Thanks for the quick work!
