### ISSUE TITLE
Issue with the generation on the pyd file in the library package

### ISSUE THREAD

**Issue by Diminati** [eerimoq/bitstruct#35]
Hello,
I am using Python 3.8 in pycharm.

Sorry in advance if I have a very superficial understanding of how this module works but installing the lastest version of bitstruct doesn't automatically generate the c.cp38-win_amd64.pyd, I would assume it's related to an error on the creation of the C code.
This file speeds use the usage of the cantool library that relies on bitstruct.
The 8.16.1 and some other previous version generates the file on my computer.

Any idea what could be the issue here?
Thank you.

**Comment by eerimoq** [comment]
Hi,

unfortunately I can't figure out what is wrong. The diff between 8.16.1 and 8.17.0 is minimal. Maybe you can track it down?

**Comment by Diminati** [comment]
Hi Erik, 
Thank you for your feedback and sorry for the late reply.
I could not figure out the issue at the time and I am not working with this project/library anymore.
I seem to be the only one with this issue so I request closure.
