### ISSUE TITLE
missing files from pypi distribution

### ISSUE THREAD

**Issue by brianmay** [eerimoq/bitstruct#4]
Hello,

A number of files are missing from the PyPI distribution, such as the tests, the license file, etc.

Can this please be fixed?

Thanks

**Comment by brianmay** [comment]
The following MANIFEST.in file should fix this:

```
include LICENSE
include Makefile
recursive-include docs *.bat
recursive-include docs *.py
recursive-include docs *.rst
recursive-include docs Makefile
recursive-include tests *.py
```

**Comment by eerimoq** [comment]
Hi,

Thanks for the notice. I added the manifest you suggested to version 2.1.3.

Enjoy!

Erik

**Comment by brianmay** [comment]
Looks good. Thanks.
