### ISSUE TITLE
Speedup using bitmasks instead of string operations

### ISSUE THREAD

**Issue by ntolazzi** [eerimoq/bitstruct#6]
Hey, I really enjoy your package but unfortunately I had to use my self written bitmask based approach for my own project because bitstruct was not fast enough for the amount of data that I have.
The thing that takes most time are the string operations like

` bits = ''.join(['{:08b}'.format(b) for b in bytearray(data)])`

But it's not necessary to do all the string operations, they make the rest of the code slightly easier to read but the library should work also solely based on bitmasks. Below is an example of what I mean:
 
```
    data = struct.unpack('>i', bytestring)[0]
    quad1 = data & 0x3fff
    quad2 = (data & 0xfffc000) >> 14
    if (quad2 & (1 << (14 - 1))) != 0:
        quad2 = quad2 - (1 << 14)
    bool0 = data & 2**31
    bool1 = data & 2**30
    bool2 = data & 2**29
    bool3 = data & 2**28
```

I first used bitstruct for this piece of code but when I replaced it with bitmasks it got faster by a factor of 6.

Just saying that it might be worth a try to realize the same funtionality of bitstruct via bitmasks.

Best,
ntolazzi

**Comment by eerimoq** [comment]
Hello,

improving the performance by 6 times with a small code change is certainly interesting and should be implemented. Please create a pull request and I'll review it, probalby merge and release.

Thanks

**Comment by ntolazzi** [comment]
Just to clarify, this would probably involve more than small changes because everywhere in the code where you access the single bits via list slicing like

`bits[offset:offset+size]`

it needs to apply a corresponding binary mask instead and then align to the right again. 
If I find time I will look into this on the weekend.

**Comment by eerimoq** [comment]
Ok, maybe there are other ways to improve the performance as well, but give it a try without putting too much time into it and submit a PR so I can have a look.

The *only* rule is not to use C-extensions as I like to have all code written in Python.

**Comment by eerimoq** [comment]
Also, the sanity checks in `pack` and `unpack` could probably be removed. They are sometimes helpful, but most of the time they just makes the performance worse.

**Comment by eerimoq** [comment]
I made a few changes that improves the performance by a factor of 2-5 depending on format string types. The changes can be found on the [performance branch](https://github.com/eerimoq/bitstruct/commit/e7d6cf8ccbb11aad4043495e6a5003bcdc2c3869). It includes pre-compiled formats and is replacing `format()` with a combination of `hex()`, `int()`, `bin()` and `binascii.hexlify()`.

So I guess performance can be improved even further using bitmasks =)

**Comment by eerimoq** [comment]
The changes are now on master.

**Comment by eerimoq** [comment]
Are you working on this, or should we close the issue?

**Comment by ntolazzi** [comment]
We can close the issue for now. I didn't find the time to work on it. But thanks again for beeing so open to new ideas and contributers.
