### ISSUE TITLE
Speedup using fixed format strings

### ISSUE THREAD

**Issue by ntolazzi** [eerimoq/bitstruct#7]
Imagine we want to use bitstruct for a very large amount of data that we want to process and convert to python types. This would involve many (in my case on the order of 1e9) calls to unpack and/or pack function. In this function it alsways parses the fmt string. I would propose to put these functions into a class and therefore give the ability to store i.e. the result of the fmt string parsing for subsequent calls with new data. This would definitely save quite some time.

If you agree with this idea to change it into a class maybe to allow a more stateful approach, I would try to do it and make a PR.

Best,
ntolazzi

**Comment by eerimoq** [comment]
I've had plans to do extend the interface with a compile-function, inspired by the re module. A pull request with functionality to "compile" the format string once and then use it many times is welcome and will likely be accepted. Just try to keep it as clean as possible as I like easy to understand interfaces.

**Comment by eerimoq** [comment]
This is part of release [3.5.0](https://pypi.python.org/pypi/bitstruct/3.5.0)! =)
