### ISSUE TITLE
Please add a pack_into() function

### ISSUE THREAD

**Issue by henzef** [eerimoq/bitstruct#9]
The standard libary module "struct" has a handy .pack_into() function (see [https://docs.python.org/3/library/struct.html?highlight=pack_into#functions-and-exceptions](https://docs.python.org/3/library/struct.html?highlight=pack_into#functions-and-exceptions). This is usefull when modifying existing buffers with lots of dont-care fields (aka padding) that should be preserved.

Please add such a function to bitstruct.

**Comment by eerimoq** [comment]
Seems the struct module's pack_into-function overwrites padding bytes ('x' in the format string) with 0. I'll do the same for padding bits in bitstruct. Or?

**Comment by henzef** [comment]
Oops, thats correct. The behaviour I described would still be useful. maybe add a keyword argument? .pack_into(fmt, offset, *args, fill_padding=True)?

**Comment by henzef** [comment]
My _actual_ intention is being able to pack data formats that require (or at least recommend) padding to be all ones. I thought implementing a pack_into as described here would do the job for me and would enable other use cases as well.
The easiest way to cover my use case would be to add a new character to the format string (e.g. an uppercase P), which does padding with ones. What's the better solution?

**Comment by eerimoq** [comment]
I think I'll accept the pull request, but `pack_into()` with optional overwrite sounds useful as well. I think we should add that as well.

**Comment by eerimoq** [comment]
Fix the code style comment in you PR, and I'll merge it.

**Comment by flyser** [comment]
I will, but I don't have access to my github work account till monday.

**Comment by eerimoq** [comment]
Created a new release, 3.8.0, including your changes and `pack_into()` and `unpack_from()`.

Thanks.
